### ISSUE TITLE
建议：默认支持同时搜索路径下的子文件夹

### ISSUE THREAD

**Issue by sls463** [Roy0309/ImageSimilarityDetection-UI#4]
尝试使用此软件时我还以为跟众多查找重复图片软件那样是默认支持同时搜索路径下的子文件夹内的图片，但后来发现有效图片
数较少，我去摸索找原因(见下附图1~3)才知道此软件目前只搜索母文件夹下的图片，感觉使用起来有些“繁琐”或者说不是很方
便，如果能支持同时搜索路径下的子文件夹(参考下附图4)，那就更好了，这样新用户使用体验会更好(目前是：由于不知道不支持
搜索子文件夹，看到只找到少量重复结果，很容易误以为此软件不够给力)

举个例子：我收藏 篠崎愛Ai Shinozaki 的写真集，母文件夹下有212张零散图片+117个子文件夹，如果支持搜索子文件夹，只需
拖入母文件夹一个动作即可；目前不支持搜索子文件夹，所以还得再将117个子文件夹选中后拖入；还好已实现了拖拽添加，不然
按v1.2版那种方式添加100多个文件夹，那真是够呛的，呵呵

![111](https://user-images.githubusercontent.com/41649803/136903839-276f0c9c-c150-4f90-8151-6ced4a26148d.jpg)
![222](https://user-images.githubusercontent.com/41649803/136903872-eaa5739b-7d28-4dc9-8add-5ac5c528b77f.jpg)
![333](https://user-images.githubusercontent.com/41649803/136903899-94cb7820-4bd4-4ae9-9a1e-047450c1b26a.jpg)
![444](https://user-images.githubusercontent.com/41649803/136903914-eeaddc57-a336-4db0-a294-a827aa9d5946.jpg)

**Comment by Roy0309** [comment]
你好，1.4 版已支持子文件夹。
